# TCL File Generated by Component Editor 9.1sp2
# Wed Jun 02 14:04:26 CST 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | LCD_SINK "LCD_SINK" v1.0
# | null 2010.06.02.14:04:26
# | 
# | 
# | D:/DE3_340_LCD/ip/TERASIC_LCD_SINK/LCD_SINK.v
# | 
# |    ./LCD_SINK.v syn, sim
# |    ./lcd_fifo.v syn, sim
# |    ./lcd_timing_controller.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 9.1
# | 
package require -exact sopc 9.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module LCD_SINK
# | 
set_module_property NAME LCD_SINK
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP ""
set_module_property DISPLAY_NAME LCD_SINK
set_module_property TOP_LEVEL_HDL_FILE LCD_SINK.v
set_module_property TOP_LEVEL_HDL_MODULE LCD_SINK
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file LCD_SINK.v {SYNTHESIS SIMULATION}
add_file lcd_fifo.v {SYNTHESIS SIMULATION}
add_file lcd_timing_controller.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter SYMBOLS_PER_BEAT INTEGER 3
set_parameter_property SYMBOLS_PER_BEAT DEFAULT_VALUE 3
set_parameter_property SYMBOLS_PER_BEAT DISPLAY_NAME SYMBOLS_PER_BEAT
set_parameter_property SYMBOLS_PER_BEAT UNITS None
set_parameter_property SYMBOLS_PER_BEAT DISPLAY_HINT ""
set_parameter_property SYMBOLS_PER_BEAT AFFECTS_GENERATION false
set_parameter_property SYMBOLS_PER_BEAT HDL_PARAMETER true
add_parameter BITS_PER_SYMBOL INTEGER 8
set_parameter_property BITS_PER_SYMBOL DEFAULT_VALUE 8
set_parameter_property BITS_PER_SYMBOL DISPLAY_NAME BITS_PER_SYMBOL
set_parameter_property BITS_PER_SYMBOL UNITS None
set_parameter_property BITS_PER_SYMBOL DISPLAY_HINT ""
set_parameter_property BITS_PER_SYMBOL AFFECTS_GENERATION false
set_parameter_property BITS_PER_SYMBOL HDL_PARAMETER true
add_parameter READY_LATENCY INTEGER 0
set_parameter_property READY_LATENCY DEFAULT_VALUE 0
set_parameter_property READY_LATENCY DISPLAY_NAME READY_LATENCY
set_parameter_property READY_LATENCY UNITS None
set_parameter_property READY_LATENCY DISPLAY_HINT ""
set_parameter_property READY_LATENCY AFFECTS_GENERATION false
set_parameter_property READY_LATENCY HDL_PARAMETER true
add_parameter MAX_CHANNEL INTEGER 0
set_parameter_property MAX_CHANNEL DEFAULT_VALUE 0
set_parameter_property MAX_CHANNEL DISPLAY_NAME MAX_CHANNEL
set_parameter_property MAX_CHANNEL UNITS None
set_parameter_property MAX_CHANNEL DISPLAY_HINT ""
set_parameter_property MAX_CHANNEL AFFECTS_GENERATION false
set_parameter_property MAX_CHANNEL HDL_PARAMETER true
add_parameter STATE_IDLE INTEGER 0
set_parameter_property STATE_IDLE DEFAULT_VALUE 0
set_parameter_property STATE_IDLE DISPLAY_NAME STATE_IDLE
set_parameter_property STATE_IDLE UNITS None
set_parameter_property STATE_IDLE DISPLAY_HINT ""
set_parameter_property STATE_IDLE AFFECTS_GENERATION false
set_parameter_property STATE_IDLE HDL_PARAMETER true
add_parameter STATE_RESET INTEGER 1
set_parameter_property STATE_RESET DEFAULT_VALUE 1
set_parameter_property STATE_RESET DISPLAY_NAME STATE_RESET
set_parameter_property STATE_RESET UNITS None
set_parameter_property STATE_RESET DISPLAY_HINT ""
set_parameter_property STATE_RESET AFFECTS_GENERATION false
set_parameter_property STATE_RESET HDL_PARAMETER true
add_parameter STATE_STREAMING INTEGER 2
set_parameter_property STATE_STREAMING DEFAULT_VALUE 2
set_parameter_property STATE_STREAMING DISPLAY_NAME STATE_STREAMING
set_parameter_property STATE_STREAMING UNITS None
set_parameter_property STATE_STREAMING DISPLAY_HINT ""
set_parameter_property STATE_STREAMING AFFECTS_GENERATION false
set_parameter_property STATE_STREAMING HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment DYNAMIC
set_interface_property avalon_slave_0 associatedClock clock_reset
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ASSOCIATED_CLOCK clock_reset
set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 address_in address Input 3
add_interface_port avalon_slave_0 read_in read Input 1
add_interface_port avalon_slave_0 readdata_out readdata Output 16
add_interface_port avalon_slave_0 write_in write Input 1
add_interface_port avalon_slave_0 writedata_in writedata Input 16
add_interface_port avalon_slave_0 cs_in chipselect_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset clk clk Input 1
add_interface_port clock_reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_streaming_sink
# | 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock_reset
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0

set_interface_property avalon_streaming_sink ASSOCIATED_CLOCK clock_reset
set_interface_property avalon_streaming_sink ENABLED true

add_interface_port avalon_streaming_sink ready_out ready Output 1
add_interface_port avalon_streaming_sink valid_in valid Input 1
add_interface_port avalon_streaming_sink data_in data Input 24
add_interface_port avalon_streaming_sink sop_in startofpacket Input 1
add_interface_port avalon_streaming_sink eop_in endofpacket Input 1
add_interface_port avalon_streaming_sink empty_in empty Input 2
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end lcd_clk_external export Input 1
add_interface_port conduit_end lcd_hd export Output 1
add_interface_port conduit_end lcd_vd export Output 1
add_interface_port conduit_end lcd_de export Output 1
add_interface_port conduit_end lcd_data export Output 8
add_interface_port conduit_end lcd_test_pattern export Input 1
# | 
# +-----------------------------------
