# TCL File Generated by Component Editor 7.2sp1 on:
# Thu Jan 10 13:03:21 CST 2008
# DO NOT MODIFY

set_source_file "ISP1761_IF.v"
set_module "ISP1761_IF"
set_module_description "ISP1761 Interface"
set_module_property "displayName" "ISP1761 Interface"
set_module_property "className" "ISP1761"
set_module_property "group" "Terasic Technologies Inc."
set_module_property "instantiateInSystemModule" "true"
set_module_property "synthesisFiles" "ISP1761_IF.v"
set_module_property editable "false"

# Module parameters

# Interface clock
add_interface "clock" "clock" "sink" "asynchronous"
# Ports in interface clock

# Interface usb
add_interface "usb" "conduit" "start" "clock"
# Ports in interface usb
add_port_to_interface "usb" "CS_N" "export"
add_port_to_interface "usb" "WR_N" "export"
add_port_to_interface "usb" "RD_N" "export"
add_port_to_interface "usb" "D" "export"
add_port_to_interface "usb" "A" "export"
add_port_to_interface "usb" "DC_IRQ" "export"
add_port_to_interface "usb" "HC_IRQ" "export"
add_port_to_interface "usb" "DC_DREQ" "export"
add_port_to_interface "usb" "HC_DREQ" "export"
add_port_to_interface "usb" "DC_DACK" "export"
add_port_to_interface "usb" "HC_DACK" "export"

# Interface slave
add_interface "slave" "avalon" "slave" "clock"
set_interface_property "slave" "isNonVolatileStorage" "false"
set_interface_property "slave" "burstOnBurstBoundariesOnly" "false"
set_interface_property "slave" "readLatency" "0"
set_interface_property "slave" "readWaitStates" "70"
set_interface_property "slave" "holdTime" "10"
set_interface_property "slave" "printableDevice" "false"
set_interface_property "slave" "readWaitTime" "70"
set_interface_property "slave" "setupTime" "10"
set_interface_property "slave" "addressAlignment" "NATIVE"
set_interface_property "slave" "writeWaitTime" "70"
set_interface_property "slave" "timingUnits" "Nanoseconds"
set_interface_property "slave" "minimumUninterruptedRunLength" "1"
set_interface_property "slave" "isMemoryDevice" "false"
set_interface_property "slave" "linewrapBursts" "false"
set_interface_property "slave" "writeWaitStates" "70"
set_interface_property "slave" "maximumPendingReadTransactions" "0"
# Ports in interface slave
add_port_to_interface "slave" "s_address" "address"
add_port_to_interface "slave" "s_write_n" "write_n"
add_port_to_interface "slave" "s_writedata" "writedata"
add_port_to_interface "slave" "s_read_n" "read_n"
add_port_to_interface "slave" "s_readdata" "readdata"
add_port_to_interface "slave" "s_cs_n" "chipselect_n"


# Interface interrupt_sender_hc
add_interface "interrupt_sender_hc" "interrupt" "sender" "asynchronous"
#add_interface "interrupt_sender_hc" "interrupt" "sender" "global_signals_clock"
set_interface_property "interrupt_sender_hc" "associatedAddressablePoint" "slave"
# Ports in interface interrupt_sender_hc
add_port_to_interface "interrupt_sender_hc" "s_hc_irq" "irq_n"

# Interface slave_dc_irq
add_interface "slave_dc_irq" "avalon" "slave" "clock"
set_interface_property "slave_dc_irq" "isNonVolatileStorage" "false"
set_interface_property "slave_dc_irq" "burstOnBurstBoundariesOnly" "false"
set_interface_property "slave_dc_irq" "readLatency" "0"
set_interface_property "slave_dc_irq" "holdTime" "0"
set_interface_property "slave_dc_irq" "printableDevice" "false"
set_interface_property "slave_dc_irq" "readWaitTime" "0"
set_interface_property "slave_dc_irq" "setupTime" "0"
set_interface_property "slave_dc_irq" "addressAlignment" "DYNAMIC"
set_interface_property "slave_dc_irq" "writeWaitTime" "0"
set_interface_property "slave_dc_irq" "timingUnits" "Cycles"
set_interface_property "slave_dc_irq" "minimumUninterruptedRunLength" "1"
set_interface_property "slave_dc_irq" "isMemoryDevice" "false"
set_interface_property "slave_dc_irq" "linewrapBursts" "false"
set_interface_property "slave_dc_irq" "maximumPendingReadTransactions" "0"
# Ports in interface slave_dc_irq
add_port_to_interface "slave_dc_irq" "s_dc_readdata" "readdata"

# Interface interrupt_sender_dc
add_interface "interrupt_sender_dc" "interrupt" "sender" "asynchronous"
#add_interface "interrupt_sender_dc" "interrupt" "sender" "global_signals_clock"
set_interface_property "interrupt_sender_dc" "associatedAddressablePoint" "slave_dc_irq"
# Ports in interface interrupt_sender_dc
add_port_to_interface "interrupt_sender_dc" "s_dc_irq" "irq_n"
