# TCL File Generated by Component Editor on: 
# Wed Sep 19 08:28:23 CST 2007
# DO NOT MODIFY

set_source_file "SEG7_IF.v"
set_module "SEG7_IF"
set_module_description ""
set_module_property instantiateInSystemModule true
set_module_property version "1.0"
set_module_property group "Terasic Technologies Inc."
set_module_property editable true

# Module parameters
add_parameter "SEG7_NUM" "integer" "8" ""
add_parameter "ADDR_WIDTH" "integer" "3" ""
add_parameter "DEFAULT_ACTIVE" "integer" "1" ""
add_parameter "LOW_ACTIVE" "integer" "1" ""

# Clock Interface s1_clock
add_clock_interface "s1_clock" 
set_interface_property "s1_clock" "externallyDriven" "false"
set_interface_property "s1_clock" "clockRateKnown" "false"
set_interface_property "s1_clock" "clockRate" "0"
# Ports in interface s1_clock
add_port_to_interface "s1_clock" "avs_s1_clk" "clk"
add_port_to_interface "s1_clock" "avs_s1_reset" "reset"

# Interface s1
add_interface "s1" "avalon" "slave" "s1_clock"
set_interface_property "s1" "isNonVolatileStorage" "false"
set_interface_property "s1" "burstOnBurstBoundariesOnly" "false"
set_interface_property "s1" "transparentBridge" "false"
set_interface_property "s1" "readLatency" "0"
set_interface_property "s1" "readWaitStates" "0"
set_interface_property "s1" "isFlash" "false"
set_interface_property "s1" "holdTime" "0"
set_interface_property "s1" "printableDevice" "false"
set_interface_property "s1" "registerIncomingSignals" "false"
set_interface_property "s1" "readWaitTime" "0"
set_interface_property "s1" "setupTime" "0"
set_interface_property "s1" "addressGroup" "0"
set_interface_property "s1" "interleaveBursts" "false"
set_interface_property "s1" "addressAlignment" "NATIVE"
set_interface_property "s1" "isBigEndian" "false"
set_interface_property "s1" "writeLatency" "0"
set_interface_property "s1" "writeWaitTime" "0"
set_interface_property "s1" "timingUnits" "Cycles"
set_interface_property "s1" "minimumUninterruptedRunLength" "1"
set_interface_property "s1" "registerOutgoingSignals" "false"
set_interface_property "s1" "addressSpan" "8"
set_interface_property "s1" "isMemoryDevice" "false"
set_interface_property "s1" "linewrapBursts" "false"
set_interface_property "s1" "alwaysBurstMaxBurst" "false"
set_interface_property "s1" "writeWaitStates" "0"
set_interface_property "s1" "maximumPendingReadTransactions" "0"
set_interface_property "s1" "wellBehavedWaitrequest" "false"
# Ports in interface s1
add_port_to_interface "s1" "avs_s1_address" "address"
add_port_to_interface "s1" "avs_s1_read" "read"
add_port_to_interface "s1" "avs_s1_readdata" "readdata"
add_port_to_interface "s1" "avs_s1_write" "write"
add_port_to_interface "s1" "avs_s1_writedata" "writedata"

# Wire Interface s1_export
add_interface "s1_export" "conduit" "output" "s1_clock"
# Ports in interface s1_export
add_port_to_interface "s1_export" "avs_s1_export_seg7" "export"
