/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'cpu' in SOPC Builder design 'nios_simple'
 * SOPC Builder design path: C:/Users/HEMA/Desktop/HARDGAME/versuchwithsdddnewwwwww/DE2_115_LTM_Pic/nios_simple.sopcinfo
 *
 * Generated: Fri Mar 29 14:51:05 CET 2024
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_qsys"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0xa410820
#define ALT_CPU_CPU_FREQ 100000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "fast"
#define ALT_CPU_DATA_ADDR_WIDTH 0x1c
#define ALT_CPU_DCACHE_LINE_SIZE 32
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_DCACHE_SIZE 2048
#define ALT_CPU_EXCEPTION_ADDR 0xa200020
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 100000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 1
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 32
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_ICACHE_SIZE 4096
#define ALT_CPU_INITDA_SUPPORTED
#define ALT_CPU_INST_ADDR_WIDTH 0x1c
#define ALT_CPU_NAME "cpu"
#define ALT_CPU_NUM_OF_SHADOW_REG_SETS 0
#define ALT_CPU_RESET_ADDR 0x9800000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0xa410820
#define NIOS2_CPU_FREQ 100000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "fast"
#define NIOS2_DATA_ADDR_WIDTH 0x1c
#define NIOS2_DCACHE_LINE_SIZE 32
#define NIOS2_DCACHE_LINE_SIZE_LOG2 5
#define NIOS2_DCACHE_SIZE 2048
#define NIOS2_EXCEPTION_ADDR 0xa200020
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 1
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 32
#define NIOS2_ICACHE_LINE_SIZE_LOG2 5
#define NIOS2_ICACHE_SIZE 4096
#define NIOS2_INITDA_SUPPORTED
#define NIOS2_INST_ADDR_WIDTH 0x1c
#define NIOS2_NUM_OF_SHADOW_REG_SETS 0
#define NIOS2_RESET_ADDR 0x9800000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_FIFO
#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_NEW_SDRAM_CONTROLLER
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_PIO
#define __ALTERA_AVALON_SGDMA
#define __ALTERA_AVALON_SPI
#define __ALTERA_AVALON_SYSID_QSYS
#define __ALTERA_AVALON_TIMER
#define __ALTERA_GENERIC_TRISTATE_CONTROLLER
#define __ALTERA_NIOS2_QSYS
#define __ALTPLL
#define __SD_CONTROLLER
#define __TERASIC_SRAM


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone IV E"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart"
#define ALT_STDERR_BASE 0xa411070
#define ALT_STDERR_DEV jtag_uart
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart"
#define ALT_STDIN_BASE 0xa411070
#define ALT_STDIN_DEV jtag_uart
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart"
#define ALT_STDOUT_BASE 0xa411070
#define ALT_STDOUT_DEV jtag_uart
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "nios_simple"


/*
 * cfi_flash configuration
 *
 */

#define ALT_MODULE_CLASS_cfi_flash altera_generic_tristate_controller
#define CFI_FLASH_BASE 0x9800000
#define CFI_FLASH_HOLD_VALUE 60
#define CFI_FLASH_IRQ -1
#define CFI_FLASH_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CFI_FLASH_NAME "/dev/cfi_flash"
#define CFI_FLASH_SETUP_VALUE 60
#define CFI_FLASH_SIZE 8388608u
#define CFI_FLASH_SPAN 8388608
#define CFI_FLASH_TIMING_UNITS "ns"
#define CFI_FLASH_TYPE "altera_generic_tristate_controller"
#define CFI_FLASH_WAIT_VALUE 160


/*
 * descriptor_mem configuration
 *
 */

#define ALT_MODULE_CLASS_descriptor_mem altera_avalon_onchip_memory2
#define DESCRIPTOR_MEM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define DESCRIPTOR_MEM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define DESCRIPTOR_MEM_BASE 0xa400000
#define DESCRIPTOR_MEM_CONTENTS_INFO ""
#define DESCRIPTOR_MEM_DUAL_PORT 0
#define DESCRIPTOR_MEM_GUI_RAM_BLOCK_TYPE "AUTO"
#define DESCRIPTOR_MEM_INIT_CONTENTS_FILE "nios_simple_descriptor_mem"
#define DESCRIPTOR_MEM_INIT_MEM_CONTENT 1
#define DESCRIPTOR_MEM_INSTANCE_ID "NONE"
#define DESCRIPTOR_MEM_IRQ -1
#define DESCRIPTOR_MEM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DESCRIPTOR_MEM_NAME "/dev/descriptor_mem"
#define DESCRIPTOR_MEM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define DESCRIPTOR_MEM_RAM_BLOCK_TYPE "AUTO"
#define DESCRIPTOR_MEM_READ_DURING_WRITE_MODE "DONT_CARE"
#define DESCRIPTOR_MEM_SINGLE_CLOCK_OP 0
#define DESCRIPTOR_MEM_SIZE_MULTIPLE 1
#define DESCRIPTOR_MEM_SIZE_VALUE 65536
#define DESCRIPTOR_MEM_SPAN 65536
#define DESCRIPTOR_MEM_TYPE "altera_avalon_onchip_memory2"
#define DESCRIPTOR_MEM_WRITABLE 1


/*
 * fifo configuration
 *
 */

#define ALT_MODULE_CLASS_fifo altera_avalon_fifo
#define FIFO_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_BASE 0xa411040
#define FIFO_BITS_PER_SYMBOL 8
#define FIFO_CHANNEL_WIDTH 0
#define FIFO_ERROR_WIDTH 0
#define FIFO_FIFO_DEPTH 512
#define FIFO_IRQ 1
#define FIFO_IRQ_INTERRUPT_CONTROLLER_ID 0
#define FIFO_NAME "/dev/fifo"
#define FIFO_SINGLE_CLOCK_MODE 0
#define FIFO_SPAN 32
#define FIFO_SYMBOLS_PER_BEAT 4
#define FIFO_TYPE "altera_avalon_fifo"
#define FIFO_USE_AVALONMM_READ_SLAVE 0
#define FIFO_USE_AVALONMM_WRITE_SLAVE 0
#define FIFO_USE_AVALONST_SINK 1
#define FIFO_USE_AVALONST_SOURCE 1
#define FIFO_USE_BACKPRESSURE 1
#define FIFO_USE_IRQ 1
#define FIFO_USE_PACKET 1
#define FIFO_USE_READ_CONTROL 0
#define FIFO_USE_REGISTER 0
#define FIFO_USE_WRITE_CONTROL 1


/*
 * hal configuration
 *
 */

#define ALT_MAX_FD 32
#define ALT_SYS_CLK SYS_CLK_TIMER
#define ALT_TIMESTAMP_CLK none


/*
 * jtag_uart configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart altera_avalon_jtag_uart
#define JTAG_UART_BASE 0xa411070
#define JTAG_UART_IRQ 2
#define JTAG_UART_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_NAME "/dev/jtag_uart"
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_SPAN 8
#define JTAG_UART_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8


/*
 * lcd_i2c_en configuration
 *
 */

#define ALT_MODULE_CLASS_lcd_i2c_en altera_avalon_pio
#define LCD_I2C_EN_BASE 0x8000450
#define LCD_I2C_EN_BIT_CLEARING_EDGE_REGISTER 0
#define LCD_I2C_EN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LCD_I2C_EN_CAPTURE 0
#define LCD_I2C_EN_DATA_WIDTH 1
#define LCD_I2C_EN_DO_TEST_BENCH_WIRING 0
#define LCD_I2C_EN_DRIVEN_SIM_VALUE 0
#define LCD_I2C_EN_EDGE_TYPE "NONE"
#define LCD_I2C_EN_FREQ 80000000
#define LCD_I2C_EN_HAS_IN 0
#define LCD_I2C_EN_HAS_OUT 1
#define LCD_I2C_EN_HAS_TRI 0
#define LCD_I2C_EN_IRQ -1
#define LCD_I2C_EN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LCD_I2C_EN_IRQ_TYPE "NONE"
#define LCD_I2C_EN_NAME "/dev/lcd_i2c_en"
#define LCD_I2C_EN_RESET_VALUE 0
#define LCD_I2C_EN_SPAN 16
#define LCD_I2C_EN_TYPE "altera_avalon_pio"


/*
 * lcd_i2c_scl configuration
 *
 */

#define ALT_MODULE_CLASS_lcd_i2c_scl altera_avalon_pio
#define LCD_I2C_SCL_BASE 0x8000440
#define LCD_I2C_SCL_BIT_CLEARING_EDGE_REGISTER 0
#define LCD_I2C_SCL_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LCD_I2C_SCL_CAPTURE 0
#define LCD_I2C_SCL_DATA_WIDTH 1
#define LCD_I2C_SCL_DO_TEST_BENCH_WIRING 0
#define LCD_I2C_SCL_DRIVEN_SIM_VALUE 0
#define LCD_I2C_SCL_EDGE_TYPE "NONE"
#define LCD_I2C_SCL_FREQ 80000000
#define LCD_I2C_SCL_HAS_IN 0
#define LCD_I2C_SCL_HAS_OUT 1
#define LCD_I2C_SCL_HAS_TRI 0
#define LCD_I2C_SCL_IRQ -1
#define LCD_I2C_SCL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LCD_I2C_SCL_IRQ_TYPE "NONE"
#define LCD_I2C_SCL_NAME "/dev/lcd_i2c_scl"
#define LCD_I2C_SCL_RESET_VALUE 0
#define LCD_I2C_SCL_SPAN 16
#define LCD_I2C_SCL_TYPE "altera_avalon_pio"


/*
 * lcd_i2c_sda configuration
 *
 */

#define ALT_MODULE_CLASS_lcd_i2c_sda altera_avalon_pio
#define LCD_I2C_SDA_BASE 0x8000460
#define LCD_I2C_SDA_BIT_CLEARING_EDGE_REGISTER 0
#define LCD_I2C_SDA_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LCD_I2C_SDA_CAPTURE 0
#define LCD_I2C_SDA_DATA_WIDTH 1
#define LCD_I2C_SDA_DO_TEST_BENCH_WIRING 0
#define LCD_I2C_SDA_DRIVEN_SIM_VALUE 0
#define LCD_I2C_SDA_EDGE_TYPE "NONE"
#define LCD_I2C_SDA_FREQ 80000000
#define LCD_I2C_SDA_HAS_IN 0
#define LCD_I2C_SDA_HAS_OUT 0
#define LCD_I2C_SDA_HAS_TRI 1
#define LCD_I2C_SDA_IRQ -1
#define LCD_I2C_SDA_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LCD_I2C_SDA_IRQ_TYPE "NONE"
#define LCD_I2C_SDA_NAME "/dev/lcd_i2c_sda"
#define LCD_I2C_SDA_RESET_VALUE 0
#define LCD_I2C_SDA_SPAN 16
#define LCD_I2C_SDA_TYPE "altera_avalon_pio"


/*
 * pll configuration
 *
 */

#define ALT_MODULE_CLASS_pll altpll
#define PLL_BASE 0xa411060
#define PLL_IRQ -1
#define PLL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PLL_NAME "/dev/pll"
#define PLL_SPAN 16
#define PLL_TYPE "altpll"


/*
 * sd_card_controller configuration
 *
 */

#define ALT_MODULE_CLASS_sd_card_controller sd_controller
#define SD_CARD_CONTROLLER_BASE 0x8000000
#define SD_CARD_CONTROLLER_IRQ -1
#define SD_CARD_CONTROLLER_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SD_CARD_CONTROLLER_NAME "/dev/sd_card_controller"
#define SD_CARD_CONTROLLER_SPAN 1024
#define SD_CARD_CONTROLLER_TYPE "sd_controller"


/*
 * sdram configuration
 *
 */

#define ALT_MODULE_CLASS_sdram altera_avalon_new_sdram_controller
#define SDRAM_BASE 0x0
#define SDRAM_CAS_LATENCY 3
#define SDRAM_CONTENTS_INFO
#define SDRAM_INIT_NOP_DELAY 0.0
#define SDRAM_INIT_REFRESH_COMMANDS 2
#define SDRAM_IRQ -1
#define SDRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SDRAM_IS_INITIALIZED 1
#define SDRAM_NAME "/dev/sdram"
#define SDRAM_POWERUP_DELAY 100.0
#define SDRAM_REFRESH_PERIOD 15.625
#define SDRAM_REGISTER_DATA_IN 1
#define SDRAM_SDRAM_ADDR_WIDTH 0x19
#define SDRAM_SDRAM_BANK_WIDTH 2
#define SDRAM_SDRAM_COL_WIDTH 10
#define SDRAM_SDRAM_DATA_WIDTH 32
#define SDRAM_SDRAM_NUM_BANKS 4
#define SDRAM_SDRAM_NUM_CHIPSELECTS 1
#define SDRAM_SDRAM_ROW_WIDTH 13
#define SDRAM_SHARED_DATA 0
#define SDRAM_SIM_MODEL_BASE 1
#define SDRAM_SPAN 134217728
#define SDRAM_STARVATION_INDICATOR 0
#define SDRAM_TRISTATE_BRIDGE_SLAVE ""
#define SDRAM_TYPE "altera_avalon_new_sdram_controller"
#define SDRAM_T_AC 5.5
#define SDRAM_T_MRD 3
#define SDRAM_T_RCD 20.0
#define SDRAM_T_RFC 70.0
#define SDRAM_T_RP 20.0
#define SDRAM_T_WR 14.0


/*
 * sdram configuration as viewed by sgdma_pixel_m_read
 *
 */

#define SGDMA_PIXEL_M_READ_SDRAM_BASE 0x0
#define SGDMA_PIXEL_M_READ_SDRAM_CAS_LATENCY 3
#define SGDMA_PIXEL_M_READ_SDRAM_CONTENTS_INFO
#define SGDMA_PIXEL_M_READ_SDRAM_INIT_NOP_DELAY 0.0
#define SGDMA_PIXEL_M_READ_SDRAM_INIT_REFRESH_COMMANDS 2
#define SGDMA_PIXEL_M_READ_SDRAM_IRQ -1
#define SGDMA_PIXEL_M_READ_SDRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SGDMA_PIXEL_M_READ_SDRAM_IS_INITIALIZED 1
#define SGDMA_PIXEL_M_READ_SDRAM_NAME "/dev/sdram"
#define SGDMA_PIXEL_M_READ_SDRAM_POWERUP_DELAY 100.0
#define SGDMA_PIXEL_M_READ_SDRAM_REFRESH_PERIOD 15.625
#define SGDMA_PIXEL_M_READ_SDRAM_REGISTER_DATA_IN 1
#define SGDMA_PIXEL_M_READ_SDRAM_SDRAM_ADDR_WIDTH 0x19
#define SGDMA_PIXEL_M_READ_SDRAM_SDRAM_BANK_WIDTH 2
#define SGDMA_PIXEL_M_READ_SDRAM_SDRAM_COL_WIDTH 10
#define SGDMA_PIXEL_M_READ_SDRAM_SDRAM_DATA_WIDTH 32
#define SGDMA_PIXEL_M_READ_SDRAM_SDRAM_NUM_BANKS 4
#define SGDMA_PIXEL_M_READ_SDRAM_SDRAM_NUM_CHIPSELECTS 1
#define SGDMA_PIXEL_M_READ_SDRAM_SDRAM_ROW_WIDTH 13
#define SGDMA_PIXEL_M_READ_SDRAM_SHARED_DATA 0
#define SGDMA_PIXEL_M_READ_SDRAM_SIM_MODEL_BASE 1
#define SGDMA_PIXEL_M_READ_SDRAM_SPAN 134217728
#define SGDMA_PIXEL_M_READ_SDRAM_STARVATION_INDICATOR 0
#define SGDMA_PIXEL_M_READ_SDRAM_TRISTATE_BRIDGE_SLAVE ""
#define SGDMA_PIXEL_M_READ_SDRAM_TYPE "altera_avalon_new_sdram_controller"
#define SGDMA_PIXEL_M_READ_SDRAM_T_AC 5.5
#define SGDMA_PIXEL_M_READ_SDRAM_T_MRD 3
#define SGDMA_PIXEL_M_READ_SDRAM_T_RCD 20.0
#define SGDMA_PIXEL_M_READ_SDRAM_T_RFC 70.0
#define SGDMA_PIXEL_M_READ_SDRAM_T_RP 20.0
#define SGDMA_PIXEL_M_READ_SDRAM_T_WR 14.0


/*
 * sgdma_pixel configuration
 *
 */

#define ALT_MODULE_CLASS_sgdma_pixel altera_avalon_sgdma
#define SGDMA_PIXEL_ADDRESS_WIDTH 32
#define SGDMA_PIXEL_ALWAYS_DO_MAX_BURST 1
#define SGDMA_PIXEL_ATLANTIC_CHANNEL_DATA_WIDTH 4
#define SGDMA_PIXEL_AVALON_MM_BYTE_REORDER_MODE 0
#define SGDMA_PIXEL_BASE 0xa411000
#define SGDMA_PIXEL_BURST_DATA_WIDTH 8
#define SGDMA_PIXEL_BURST_TRANSFER 0
#define SGDMA_PIXEL_BYTES_TO_TRANSFER_DATA_WIDTH 16
#define SGDMA_PIXEL_CHAIN_WRITEBACK_DATA_WIDTH 32
#define SGDMA_PIXEL_COMMAND_FIFO_DATA_WIDTH 104
#define SGDMA_PIXEL_CONTROL_DATA_WIDTH 8
#define SGDMA_PIXEL_CONTROL_SLAVE_ADDRESS_WIDTH 0x4
#define SGDMA_PIXEL_CONTROL_SLAVE_DATA_WIDTH 32
#define SGDMA_PIXEL_DESCRIPTOR_READ_BURST 0
#define SGDMA_PIXEL_DESC_DATA_WIDTH 32
#define SGDMA_PIXEL_HAS_READ_BLOCK 1
#define SGDMA_PIXEL_HAS_WRITE_BLOCK 0
#define SGDMA_PIXEL_IN_ERROR_WIDTH 0
#define SGDMA_PIXEL_IRQ 0
#define SGDMA_PIXEL_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SGDMA_PIXEL_NAME "/dev/sgdma_pixel"
#define SGDMA_PIXEL_OUT_ERROR_WIDTH 0
#define SGDMA_PIXEL_READ_BLOCK_DATA_WIDTH 32
#define SGDMA_PIXEL_READ_BURSTCOUNT_WIDTH 4
#define SGDMA_PIXEL_SPAN 64
#define SGDMA_PIXEL_STATUS_TOKEN_DATA_WIDTH 24
#define SGDMA_PIXEL_STREAM_DATA_WIDTH 32
#define SGDMA_PIXEL_SYMBOLS_PER_BEAT 4
#define SGDMA_PIXEL_TYPE "altera_avalon_sgdma"
#define SGDMA_PIXEL_UNALIGNED_TRANSFER 0
#define SGDMA_PIXEL_WRITE_BLOCK_DATA_WIDTH 32
#define SGDMA_PIXEL_WRITE_BURSTCOUNT_WIDTH 4


/*
 * sram configuration
 *
 */

#define ALT_MODULE_CLASS_sram TERASIC_SRAM
#define SRAM_BASE 0xa200000
#define SRAM_IRQ -1
#define SRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SRAM_NAME "/dev/sram"
#define SRAM_SPAN 2097152
#define SRAM_TYPE "TERASIC_SRAM"


/*
 * sys_clk_timer configuration
 *
 */

#define ALT_MODULE_CLASS_sys_clk_timer altera_avalon_timer
#define SYS_CLK_TIMER_ALWAYS_RUN 0
#define SYS_CLK_TIMER_BASE 0x8000400
#define SYS_CLK_TIMER_COUNTER_SIZE 32
#define SYS_CLK_TIMER_FIXED_PERIOD 0
#define SYS_CLK_TIMER_FREQ 80000000
#define SYS_CLK_TIMER_IRQ 3
#define SYS_CLK_TIMER_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SYS_CLK_TIMER_LOAD_VALUE 799999
#define SYS_CLK_TIMER_MULT 0.0010
#define SYS_CLK_TIMER_NAME "/dev/sys_clk_timer"
#define SYS_CLK_TIMER_PERIOD 10
#define SYS_CLK_TIMER_PERIOD_UNITS "ms"
#define SYS_CLK_TIMER_RESET_OUTPUT 0
#define SYS_CLK_TIMER_SNAPSHOT 1
#define SYS_CLK_TIMER_SPAN 32
#define SYS_CLK_TIMER_TICKS_PER_SEC 100.0
#define SYS_CLK_TIMER_TIMEOUT_PULSE_OUTPUT 0
#define SYS_CLK_TIMER_TYPE "altera_avalon_timer"


/*
 * sysid configuration
 *
 */

#define ALT_MODULE_CLASS_sysid altera_avalon_sysid_qsys
#define SYSID_BASE 0xa411078
#define SYSID_ID 0
#define SYSID_IRQ -1
#define SYSID_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYSID_NAME "/dev/sysid"
#define SYSID_SPAN 8
#define SYSID_TIMESTAMP 1711720152
#define SYSID_TYPE "altera_avalon_sysid_qsys"


/*
 * touch_panel_busy configuration
 *
 */

#define ALT_MODULE_CLASS_touch_panel_busy altera_avalon_pio
#define TOUCH_PANEL_BUSY_BASE 0x8000480
#define TOUCH_PANEL_BUSY_BIT_CLEARING_EDGE_REGISTER 0
#define TOUCH_PANEL_BUSY_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TOUCH_PANEL_BUSY_CAPTURE 0
#define TOUCH_PANEL_BUSY_DATA_WIDTH 1
#define TOUCH_PANEL_BUSY_DO_TEST_BENCH_WIRING 0
#define TOUCH_PANEL_BUSY_DRIVEN_SIM_VALUE 0
#define TOUCH_PANEL_BUSY_EDGE_TYPE "NONE"
#define TOUCH_PANEL_BUSY_FREQ 80000000
#define TOUCH_PANEL_BUSY_HAS_IN 1
#define TOUCH_PANEL_BUSY_HAS_OUT 0
#define TOUCH_PANEL_BUSY_HAS_TRI 0
#define TOUCH_PANEL_BUSY_IRQ -1
#define TOUCH_PANEL_BUSY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TOUCH_PANEL_BUSY_IRQ_TYPE "NONE"
#define TOUCH_PANEL_BUSY_NAME "/dev/touch_panel_busy"
#define TOUCH_PANEL_BUSY_RESET_VALUE 0
#define TOUCH_PANEL_BUSY_SPAN 16
#define TOUCH_PANEL_BUSY_TYPE "altera_avalon_pio"


/*
 * touch_panel_pen_irq_n configuration
 *
 */

#define ALT_MODULE_CLASS_touch_panel_pen_irq_n altera_avalon_pio
#define TOUCH_PANEL_PEN_IRQ_N_BASE 0x8000470
#define TOUCH_PANEL_PEN_IRQ_N_BIT_CLEARING_EDGE_REGISTER 0
#define TOUCH_PANEL_PEN_IRQ_N_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TOUCH_PANEL_PEN_IRQ_N_CAPTURE 1
#define TOUCH_PANEL_PEN_IRQ_N_DATA_WIDTH 1
#define TOUCH_PANEL_PEN_IRQ_N_DO_TEST_BENCH_WIRING 0
#define TOUCH_PANEL_PEN_IRQ_N_DRIVEN_SIM_VALUE 0
#define TOUCH_PANEL_PEN_IRQ_N_EDGE_TYPE "FALLING"
#define TOUCH_PANEL_PEN_IRQ_N_FREQ 80000000
#define TOUCH_PANEL_PEN_IRQ_N_HAS_IN 1
#define TOUCH_PANEL_PEN_IRQ_N_HAS_OUT 0
#define TOUCH_PANEL_PEN_IRQ_N_HAS_TRI 0
#define TOUCH_PANEL_PEN_IRQ_N_IRQ 5
#define TOUCH_PANEL_PEN_IRQ_N_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TOUCH_PANEL_PEN_IRQ_N_IRQ_TYPE "EDGE"
#define TOUCH_PANEL_PEN_IRQ_N_NAME "/dev/touch_panel_pen_irq_n"
#define TOUCH_PANEL_PEN_IRQ_N_RESET_VALUE 0
#define TOUCH_PANEL_PEN_IRQ_N_SPAN 16
#define TOUCH_PANEL_PEN_IRQ_N_TYPE "altera_avalon_pio"


/*
 * touch_panel_spi configuration
 *
 */

#define ALT_MODULE_CLASS_touch_panel_spi altera_avalon_spi
#define TOUCH_PANEL_SPI_BASE 0x8000420
#define TOUCH_PANEL_SPI_CLOCKMULT 1
#define TOUCH_PANEL_SPI_CLOCKPHASE 0
#define TOUCH_PANEL_SPI_CLOCKPOLARITY 0
#define TOUCH_PANEL_SPI_CLOCKUNITS "Hz"
#define TOUCH_PANEL_SPI_DATABITS 8
#define TOUCH_PANEL_SPI_DATAWIDTH 16
#define TOUCH_PANEL_SPI_DELAYMULT "1.0E-9"
#define TOUCH_PANEL_SPI_DELAYUNITS "ns"
#define TOUCH_PANEL_SPI_EXTRADELAY 0
#define TOUCH_PANEL_SPI_INSERT_SYNC 0
#define TOUCH_PANEL_SPI_IRQ 4
#define TOUCH_PANEL_SPI_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TOUCH_PANEL_SPI_ISMASTER 1
#define TOUCH_PANEL_SPI_LSBFIRST 0
#define TOUCH_PANEL_SPI_NAME "/dev/touch_panel_spi"
#define TOUCH_PANEL_SPI_NUMSLAVES 1
#define TOUCH_PANEL_SPI_PREFIX "spi_"
#define TOUCH_PANEL_SPI_SPAN 32
#define TOUCH_PANEL_SPI_SYNC_REG_DEPTH 2
#define TOUCH_PANEL_SPI_TARGETCLOCK 32000u
#define TOUCH_PANEL_SPI_TARGETSSDELAY "0.0"
#define TOUCH_PANEL_SPI_TYPE "altera_avalon_spi"

#endif /* __SYSTEM_H_ */
